### ISSUE TITLE
Update for 6.3

### ISSUE THREAD

**Issue by zbee** [fitzchivalrik/compass#18]
Please update the DalamudApi to 8 and .NET 7, I imagine more ClientStructs changes will be required

**Comment by fitzchivalrik** [comment]
It, unfortunately, crashes when trying to display a texture (handle) from the game, and I was not able to figure out why, for now.

**Comment by zbee** [comment]
I hope it's something you're able to figure out without too much difficulty when you have the time!
For some reason this is the only way I can keep my bearings in fights well haha
Thanks for your efforts :)

**Comment by fitzchivalrik** [comment]
Already fixed in Clientstructs, now Dalamud just needs to update.

**Comment by Kitsune-Witch** [comment]
any idea how much longer the update might be? dalamud has been updated for over a week now.

**Comment by fitzchivalrik** [comment]
As of 2023-01-21, Dalamud stable still had not the needed ClientStructs update.

**Comment by fitzchivalrik** [comment]
Dalamud's updated, plugin should be available soon :tm:
