### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by daynashaw** [fitzchivalrik/compass#19]
Hello.

I've been looking over this repo and around the internet for a few days and I can't figure out how to actually install this. How would I go about that? Thank you much!

**Comment by fitzchivalrik** [comment]
Compass is a plugin for Dalamud, installable via the in-game plugin browser. [^1]. To launch FFXIV with Dalamud, get the FFXIVQuickLauncher and start with addons enabled.
See [here](https://github.com/goatcorp/FFXIVQuickLauncher#how-to-install-the-launcher).
I unfortunately cannot provide further support on how to install plugins in general.

[^1]: Though the current update is not yet findable there, as Dalamud needs to be updated.

**Comment by daynashaw** [comment]
I see if I'm understanding correctly, your addon would normally appear in the list of addons, but it isn't right now due to some kind of compatibility thing. But when it is working again I can just install from Dalmund browser? Okay. Cool thanks.

**Comment by fitzchivalrik** [comment]
Yes, but everything's now updated; Compass is available in Dalamud's plugin browser again.
