### ISSUE TITLE
multi-monitor 

### ISSUE THREAD

**Issue by jbgit1359** [fitzchivalrik/compass#20]
When using the Dalamud option Enable multi-monitor windows compass disappears, is it possible to enable multi-monitor support for compass?

**Comment by fitzchivalrik** [comment]
I enforce the main window, as I saw no use case to having a compass on the second monitor.
Could you elaborate a little more, on why you want that?

It is very unlikely that I will remove the enforcement (I am not 100% sure what could potentially break by removing the 'always main window' assumption), but having a clearer idea of the use case makes me more likely to consider it in the future.

**Comment by jbgit1359** [comment]
I agree there is no need to be on another monitor, my issue is that when I have multi-monitor enabled compass disappears.  I prefer to have it on my main monitor (same as game). I have no issue having it locked to the same monitor as the game but I would like to be able to put other add on windows on a second monitor and not have compass disappear.

**Comment by fitzchivalrik** [comment]
Well, that's a bug - I have multi-monitor, too, but compass in main window.
Did you try the 'Center horizontally' button and playing with the position values?
Off the top of my head, I would assume the values are not correct any more, after enabling multi-monitor support, and compass' position is outside the main window - which would result in it not being visible any more.

**Comment by jbgit1359** [comment]
I did try using 'Center Horizontally' and I wasn't able to get it to show up playing with position values, I then tried the left side position value and kept dragging it until 3537 and that brought it to the center in windowed mode. I'm using windowed full screen in the game and my monitors are 2560x1440.  So I suspect the issue is somewhere in there.  I was able to get it working now, thank you for all your help.

**Comment by fitzchivalrik** [comment]
I will close this, as the initial issue was solved.
However, I will mark in my notes to have another look at the code for multi-monitor setups - in my dual setup, the values are correctly set up to only take the main FFXIV window into account, so I am unsure why's that not the case for you.
Per chance, did you set up a virtual desktop spanning both your monitors?

**Comment by jbgit1359** [comment]
I have triple monitors, no virtual, all extended. All monitors are same model, Viewsonic VX2768-2KPC and are being driven by an Nvidia 3070ti at 2560x1440.  I have FFXIV on my middle monitor.

**Comment by fitzchivalrik** [comment]
Thanks for the additional information.
