### ISSUE TITLE
Compass Icons appear to be misaligned

### ISSUE THREAD

**Issue by zbee** [fitzchivalrik/compass#26]
As you can see from the images below it does not seem like the cardinal directions' offsets are quite right, leading to them appearing misaligned - some closer to each other than others, others not aligned to the center marker. West is particularly egregious.

I have an icon pack affecting these, but [Frost UI](https://github.com/Sevii77/frost_ui) appears to be correct, especially when looking at other peoples' maps.

North is alright, East is good; but South is off, and West is way off.

<img src="https://github.com/user-attachments/assets/cbd63011-3f04-4a6a-b032-e7fdd6713251" style="width:49%" />
<img src="https://github.com/user-attachments/assets/0d97b615-7932-41d0-a1cf-70b91f69f0b1" style="width:49%" />
<img src="https://github.com/user-attachments/assets/a2254306-e756-4389-99d6-193c9a4b39d4" style="width:49%" />
<img src="https://github.com/user-attachments/assets/d7cfde04-c224-4d33-9c72-dea2c6e62103" style="width:49%" />

![image](https://github.com/user-attachments/assets/f54cc9c2-5c40-4133-96f0-150d5090acfc)

**Comment by zbee** [comment]
[Frost UI's reply](https://github.com/Sevii77/frost_ui/issues/5#issuecomment-2227327944) suggesting Compass centers the icons on visible pixels.

Is this an enhancement that would be considered?

**Comment by fitzchivalrik** [comment]
Thanks for trying out the plugin!
As you noticed, the values are aligned for the regular Game UI textures. Using UI mods results in the experience you described.
Unfortunately, I am not sure how I would go about aligning them to the visible pixels. If you have an article or such were techniques are explained, I might take a look.
However, currently I do not see myself adding support for UI mods.
