### ISSUE TITLE
[Help] Icons are not showing since Dawntrails

### ISSUE THREAD

**Issue by eaganlai** [fitzchivalrik/compass#27]
Icons are not showing since Dawntrail. Am I missing anything?
None of the icons are working for me, I even tried remove the filers for things like porters and merchants.

![image](https://github.com/user-attachments/assets/61a181eb-c670-4f06-803e-826284088e60)
![image](https://github.com/user-attachments/assets/4568b39e-9ab1-4cae-8016-8c68f499e3ef)
![image](https://github.com/user-attachments/assets/4f0fab1f-81a8-4f5f-baa9-deaef705774e)

**Comment by fitzchivalrik** [comment]
Hi, thanks for using the plugin and sorry that your are experiencing problems.
There seems to maybe be something funky with the filters, I turned them all on but _still_ saw the quest marker, while you did not o.O

Thanks for the already provided information, could you also tell me:
- Which area was it?
- What is the icon id of the circled icon? (See ReadMe on how to get icon ids.)
![image](https://github.com/user-attachments/assets/cb4a25de-be81-4f59-9eb7-dd752f929db3)
- What quest was it?

**Comment by eaganlai** [comment]
They were Ananta tribe daily, so it is The Fringes, I forgot which one tho.

My compass area is as clean as possible, no matter where I go, it is only NESW there. I can stream my screen with you over discord if it would be helpful!

**Comment by fitzchivalrik** [comment]
Thanks, I keep that offer in mind!

**Comment by eaganlai** [comment]
Just wanna say everything is back with the latest update (v1.28.1)!
