### ISSUE TITLE
[Feature Request] Add current weather icon on one of the sides

### ISSUE THREAD

**Issue by steponmepls** [fitzchivalrik/compass#3]
I'm considering replacing the minimap completely with compass and a little feature that is still missing is the ability to still display the current weather icon. I tried looking for it with your inspect tool but I guess the id will still be weather-specific not to mention it's not really a map icon in the first place.

I don't know if the goal behind this project is to replace the minimap completely eventually but I thought that maybe adding the current weather icon to one of the sides would be a simple enough task that wouldn't really disrupt the minimal aesthetic of the tool.

![image](https://user-images.githubusercontent.com/63500907/120848712-6d44c100-c575-11eb-9245-fa2fa12eaff4.png)

**Comment by fitzchivalrik** [comment]
Thank you for the suggestion and the work in getting the weather node.  
I will have a look into adding it - I am unsure though if I can manage to place it such that it looks good + so far I failed to implement hover support (display current weather text on hover).

Would you also care for the hover or would the icon be enough in most cases?

**Comment by steponmepls** [comment]
Well having a description of the weather would certainly be ideal but starting with a simple visual feedback would also be appreciated. There are instances when you are not able to directly look outside to keep track of the current weather (ex when you are farming in Pyros caves) and an icon change would be a simple but fundamental visual feedback no matter if it has or not hovering tooltips telling you what is what

**Comment by fitzchivalrik** [comment]
Will be in the next release.
![](https://raw.githubusercontent.com/fitzchivalrik/compass/master/docs/weather_icon.png)
