### ISSUE TITLE
[Feature Request] Filter more Side Quest icons

### ISSUE THREAD

**Issue by andrewgxp** [fitzchivalrik/compass#4]
Hi there! In my quest to have the Compass plugin only display the cardinal directions without any icons, I would like to request that Sidequest Icons be added to the filter. 

I've not been able to verify what the IconID is from this screenshot. Is this enough to help get this added? 

![Capture](https://user-images.githubusercontent.com/38545191/120914268-0bff1980-c66b-11eb-8cb7-3964656e2567.JPG)

**Comment by fitzchivalrik** [comment]
Do you want to _only_ display the cardinals on the compass without _any_ icons at all?
'Cause there is a setting for that since v1.6 =)
![image](https://user-images.githubusercontent.com/77893938/120940635-8b015a00-c71e-11eb-88b0-1df9df1b4ca6.png)

**Comment by andrewgxp** [comment]
Wow, I completely overlooked that setting! Well, this changes everything for me lol! Okay, I think I'll be okay to close this one then, thank you! Also, I love Compass 🍡
