### ISSUE TITLE
Remember visibility

### ISSUE THREAD

**Issue by gucciBane** [fitzchivalrik/compass#5]
Heya,

This is relatively minor, but I use a macro to toggle the compass when I need it. The plugin doesn't want to remember if I've toggled it off when I load into the game, so I'm always turning it back off when I get in. Ideally, it would remember what it was set to when I logged out.

The updates have been great, thank you!

**Comment by fitzchivalrik** [comment]
Uff, thank you, that was a hiccup on my part.
The setting was intended to be permament but I totally forgot to save the config.
Fixing that is technically a _breaking change_ now so I have to think about how to best proceed.

For now, would it work if you turn the compass off in the configuration window (and thus save the default off state) and only turn it on via a macro when needed (which would _not_ save the on state and it would be off on next login).

Sorry about that.

**Comment by gucciBane** [comment]
Woops!

That does work as a workaround in the meantime though, thanks 😃

**Comment by fitzchivalrik** [comment]
I decided to add three new commmands <togglep|onp|offp> which do the same _but_ also save the configuration.
It did not feel quite right to introduce a breaking change just for that ^^.
Thanks again for reporting.
