### ISSUE TITLE
[Filter Additions] Waymarks and Map Flag

### ISSUE THREAD

**Issue by ThatsNotAName** [fitzchivalrik/compass#7]
I'm not 100% confident these are all correct but I added hyperlinks to screenshots to show my source just in case :)

### [Waymark A:](https://i.imgur.com/yzZxfQO.png)
ui/icon/060000/060474_hr1.tex

### [Waymark B:](https://i.imgur.com/6wBg2NP.png)
ui/icon/060000/060475_hr1.tex

### [Waymark C:](https://i.imgur.com/TFATIc3.png)
ui/icon/060000/060476_hr1.tex

### [Waymark D:](https://i.imgur.com/eSyZVI9.png)
ui/icon/060000/060936_hr1.tex

### [Waymark 1:](https://i.imgur.com/BS1QI7P.png)
ui/icon/060000/060931_hr1.tex

### [Waymark 2:](https://i.imgur.com/VcN6py4.png)
ui/icon/060000/060932_hr1.tex

### [Waymark 3:](https://i.imgur.com/zNzvB87.png)
ui/icon/060000/060933_hr1.tex

### [Waymark 4:](https://i.imgur.com/YT2gq5R.png)
ui/icon/060000/063904_hr1.tex

### [Map Flag:](https://i.imgur.com/iS07pyr.png)
ui/icon/060000/060561_hr1.tex

**Comment by fitzchivalrik** [comment]
Thank you!  
With how everything is currently set up, all of those are seen as 'priority' (same as e.g. ongoing quests).
Priority is everything which is always shown on the mini map, regardless of distance. When far away, the icon + an arrow is shown (I basically take everything directly from the mini map and have no logic to exclude the arrow).
Adding a filter for those icons _will still_ remove them, but _not_ the 'arrow' for when they are out of range - but will still filter them out if in range.

Is this what you want? Or was you intention to have the icon + arrow (which is a separate icon) removed?

Talking about this arrow here above the quest marker (for flags, its red, for waymarks its other colours)
![image](https://user-images.githubusercontent.com/77893938/123390242-fb233300-d59a-11eb-96cd-69f5550f0f17.png)

**Comment by ThatsNotAName** [comment]
oh yeah local is super fine I mostly just want to remove them from the compass because they crowd it up during Savage raids and if I got what you said correctly this should help with that right? In fact, them only showing when they are out of sight is probably a really good thing lol
